//TODO ADD A HEADER GUARD

#define MOVEMENT_RIGHT 0
#define MOVEMENT_UP    1
#define MOVEMENT_LEFT  2
#define MOVEMENT_DOWN  3
#define MOVEMENT_KEYS  4

#define SPEED 5

#define PI 3.14159265 //TEMP, THIS SHOULD BE ELSEWHERE??? LIKE IN A LIBRARY?


